version: '3.9'

services:
  ros_humble:
    image: ros:humble-ros-core  # Replace with the specific image version if necessary
    container_name: ros_humble_core
    environment:
      - ROS_DOMAIN_ID=0  # Set this if you need multi-robot communication, customize if needed
    #ports:
    #  - "11311:11311"  # ROS master port, if needed
    #  - "8080:8080"    # Any other ports required for your application
    user: "${UID}:${UID}"  # Run container as your host user
    volumes:
      - ./Mars-Rover/firmware:/root/firmware  # Mount Mars-Rover/firmware from host to container
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"  # Map serial devices if needed (e.g., for motor control)
    restart: unless-stopped
    tty: true
    command: /bin/bash  # Optional: you can run specific scripts instead of starting a shell

##make sure to install ros-humble-joy and opncv on startup
